# Generated by Django 5.2.3 on 2025-07-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
